
name: Terraform Execution

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3

    - name: Storing manifests in GitHub
      uses: actions/upload-artifact@v3
      with:
       name: terraformArtifacts
       path: terraform/*
        
  deploy: 
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Downloading manifests from GitHub
      uses: actions/download-artifact@v3
      with:
       name: terraformArtifacts

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        aws-access-key-id: 'ASIAQUSXWT33HTMCQSQ5'
        aws-secret-access-key: 'hMXC1zx9++9w0/dtqAg2AgVElVJXDTGwqahfNWcO'
        aws-session-token: 'FwoGZXIvYXdzEM3//////////wEaDMhiHIq50QJV4TkjgCK7AUxqapryuxk4PXrtbzi8oGiruBCmA0ImYocZf95KmPE08XZYQVcthtDa/1FZV1rz+cMKqkY5PO6473AnQgETO3clC3KBZWaYtvQjlisCYGF7PkdLb9fFz7PiCCnN9eUK0SXTxcHcGcJqY0blXLhaCONX4EDP+DKchy3o1ALm+W3oWm4IHCK/4LRO2MoSxOPR2ag6jguRj45Q28OKfyP95nDFucfZofbmWP6wpFMMEgr4k1SC8q7BODA3YOIotNTJqQYyLTCu2vU/OblTZhG2aMtEdigS247Pmvb6GjZpgdsbd2Bf6IZD4fcQlG5z3TwxPA=='

    
    - name: Validate AWS Credentials working or not
      run: |
        aws sts get-caller-identity
    - name: Execute terraform scripts to launch S3 bucket
      run: |
        terraform init
        terraform apply --auto-approve
        
    - name: Cache state files
      id: cache-state
      uses: actions/cache@v3
      with:
        path: |
          terraform.tfstate*
        key: ${{ runner.os }}-state 
